
services:
  shopcart_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_service
    command: ["sh", "/app/entrypoint.sh"]
    #disabled for traefik
    # ports:
    #   - "8008:8000"
    env_file:
      - .env
    environment:
      SKIP_MIGRATIONS: "false" 
      # ENV: development (for deployment on google cloud)
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      PRODUCT_SERVICE: ${PRODUCT_SERVICE}

    depends_on:
      - db
    working_dir: /app
    volumes:
    #mount local files so Uvicorn sees changes instantly
      - ./src:/app/src:rw
      - ./uv.lock:/app/uv.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./.cache/uv:/home/appuser/.cache/uv  # fixing permission denied errors
    restart: unless-stopped
    networks:
      - internal_net
      - shared_network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #disabled for traefik
    # ports:
    #   - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  shopcart_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_consumer
    entrypoint: []
    command: ["python", "/app/consumer.py"]
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      db:
        condition: service_healthy
      shopcart_service:  # Wait for service to run migrations first
        condition: service_started
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./consumer.py:/app/consumer.py:rw
    networks:
      - internal_net
      - shared_network
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_celery_beat
    entrypoint: []
    command: ["celery", "-A", "src.shopcart_service.celery_app", "beat", "--loglevel=info"]
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      PRODUCT_SERVICE: ${PRODUCT_SERVICE}
    depends_on:
      db:
        condition: service_healthy
      shopcart_service:
        condition: service_started
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
    networks:
      - internal_net
      - shared_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_celery_worker
    entrypoint: []
    command: ["celery", "-A", "src.shopcart_service.celery_app", "worker", "--loglevel=info"]
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      PRODUCT_SERVICE: ${PRODUCT_SERVICE}
    depends_on:
      db:
        condition: service_healthy
      shopcart_service:
        condition: service_started
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
    networks:
      - internal_net
      - shared_network
    restart: unless-stopped


networks: 
  internal_net:
    driver: bridge
  shared_network:
    external: true
    name: shared_network


volumes:
  postgres_data:
