version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #disabled for traefik
    # ports:
    #   - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./:/app:rw
      - media:/app/shop_service/media
      - staticfiles:/app/staticfiles
      
    #disabled for traefik
    # ports:
    #   - "${WEB_PORT:-8007}:8000"
    networks:
      - internal_net
      - shared_network

    labels:
      # ðŸ”’ Enable Traefik routing only for admin panel
      - "traefik.enable=true"
      
      # Route only /admin/* to this service
      - "traefik.http.routers.shop-admin.rule=Host(`shop.localhost`) && PathPrefix(`/admin`)"
      
      # Use same web entrypoint (port 80)
      - "traefik.http.routers.shop-admin.entrypoints=web"
      
      # Define the internal service port Django runs on
      - "traefik.http.services.shop-admin.loadbalancer.server.port=8000"
      
      # Optional: Strip prefix if you route via /shop/admin instead
      # - "traefik.http.middlewares.shop-strip.stripprefix.prefixes=/shop"
      # - "traefik.http.routers.shop-admin.middlewares=shop-strip"
      
      # Optional: add HTTP basic auth for extra security
      # (user = admin, password = mypass)
      # - "traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$Dvl1KsmJ$$kIDvjg0tH8ikgm0MZJ8zU/"
      # - "traefik.http.routers.shop-admin.middlewares=admin-auth"

volumes:
  pgdata:
  media:
  staticfiles:

networks:
  internal_net:
  # internal: true
    driver: bridge
  shared_network:
    # driver: bridge (despite there is a network, it tries to create a new one )
    external: true
    name: shared_network