services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #disabled for traefik
    # ports:
    #   - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  web:
    build: .
    container_name: order-service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin12345
    volumes:
      - media:/app/order_service/media
      - staticfiles:/app/staticfiles
      # Prevents local .venv from overwriting container packages
      - /app/.venv
    #disabled for traefik
    # ports:
    #   - "${WEB_PORT:-8003}:8000"
    networks:
      - internal_net
      - shared_network

    labels:
      # ðŸ”’ Enable Traefik routing only for admin panel
      - "traefik.enable=true"
      
      # Route only /admin/* to this service
      - "traefik.http.routers.order-admin.rule=Host(`order.localhost`) && PathPrefix(`/admin`)"
      
      # Use same web entrypoint (port 80)
      - "traefik.http.routers.order-admin.entrypoints=web"
      
      # Define the internal service port Django runs on
      - "traefik.http.services.order-admin.loadbalancer.server.port=8000"

volumes:
  pgdata:
  media:
  staticfiles:

networks:
  internal_net:
  # internal: true
    driver: bridge
  shared_network:
    # driver: bridge
    external: true
    name: shared_network
