version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    #disabled for traefik
    ports:
    #   - "5672:5672"    
      - "15672:15672"  #dashboard
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
    restart: always
    networks:
      - shared_network

    labels:
      # Enable Traefik
      - "traefik.enable=true"

      # Route dashboard via http://rabbitmq.localhost
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"

      # Service listens internally on 15672
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

    

networks:
  shared_network:
    external: true