services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #disabled for traefik
    # ports:
    #   - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PYTHONUNBUFFERED: 1  # to force immediate log output
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin12345
    volumes:
    #after last commit it started to make a problem
      # - ./:/app:rw 
      - media:/app/user_service/media
      - staticfiles:/app/staticfiles
    #disabled for traefik
    # ports:
    #   - "${WEB_PORT:-8005}:8000"
    networks:
      - internal_net
      - shared_network

    labels:
      - "traefik.enable=true"
      
      # Public routes (register, login via Django - no auth needed)
      - "traefik.http.routers.user-public.rule=PathPrefix(`/user/api/register`) || PathPrefix(`/user/api/login`)"
      - "traefik.http.routers.user-public.entrypoints=web"
      - "traefik.http.services.user-public.loadbalancer.server.port=8000"
      
      # Protected routes (profile, etc.)
      - "traefik.http.routers.user-api.rule=PathPrefix(`/user/api`)"
      - "traefik.http.routers.user-api.entrypoints=web"
      - "traefik.http.routers.user-api.service=user-api"
      - "traefik.http.services.user-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.user-api.middlewares=auth-verify@file"
      - "traefik.http.routers.user-api.priority=1"  # Lower priority than public routes
      
      # Docs routes (no auth)
      - "traefik.http.routers.user-docs.rule=PathPrefix(`/user/docs`) || PathPrefix(`/user/admin`)"
      - "traefik.http.routers.user-docs.entrypoints=web"
      - "traefik.http.routers.user-docs.service=user-api"
  shop_consumer:
    build: .
    container_name: user_shop_consumer
    depends_on:
      - db
      - web
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: Core.settings
      PYTHONPATH: /app
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PYTHONUNBUFFERED: 1  # to force immediate log output
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin12345
    # volumes:
      #after last commit it started to make a problem
      # - ./:/app:rw
    command: python -u Core/consumer.py 
    restart: unless-stopped
    networks:
      - internal_net
      - shared_network

volumes:
  pgdata:
  media:
  staticfiles:

networks:
  internal_net:
    driver: bridge
  shared_network:
    external: true
    name: shared_network